db:
  image: postgres
  environment:
    - POSTGRES_USER=hackdash
    - POSTGRES_PASSWORD=hackdash
web:
  build: .
  volumes:
    - .:/code
  command: bash -c "sleep 3 && go build && ./app"
  working_dir: /go/src/app
  ports:
    - "6060:8080"
  links:
    - db
